name: flutter_crm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^0.13.6
  shared_preferences: ^2.0.6
  graphql_flutter: ^5.1.2
  flutter_secure_storage: ^9.0.0
  geolocator: ^9.0.2
  yaml: ^3.1.1
  device_preview: ^1.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  js: 0.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf
        - asset: assets/fonts/PublicSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PublicSans-Medium.ttf
        - asset: assets/fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PublicSans-Light.ttf
          weight: 300
